name: Deploy Ozma via Docker Container

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: self-hosted
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Run Flake8 with Reviewdog
        uses: reviewdog/action-flake8@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-check
          args: --config=setup.cfg
          level: warning

  deploy:
    runs-on: self-hosted
    needs: lint

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKER_IMAGE_NAME }}:latest
          build-args: |
            GH_USERNAME=${{ secrets.GH_USERNAME }}
            GH_ACCESS_TOKEN=${{ secrets.GH_ACCESS_TOKEN }}
            GH_REPO=${{ secrets.GH_REPO }}
            token=${{ secrets.TOKEN }}

      - name: Deploy with Docker Compose
        run: |
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKER_IMAGE_NAME }}:latest
          echo "token=${{ secrets.TOKEN }}" > .env
          echo "DOCKERHUB_USERNAME=${{ secrets.DOCKERHUB_USERNAME }}" >> .env
          echo "DOCKER_IMAGE_NAME=${{ secrets.DOCKER_IMAGE_NAME }}" >> .env
          echo "error_channel_id=${{ secrets.ERROR_CHANNEL_ID }}" >> .env
          echo "guild_id=${{ secrets.GUILD_ID }}" >> .env
          docker compose up -d
